
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL} # Update with your DB credentials
      SECRET: ${SECRET}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["sh", "-c", "npx prisma migrate dev --name init && npx prisma generate && npm run start:dev"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
